package models;
// Generated Jun 23, 2015 12:50:21 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer bookId;
     private String bookTitle;
     private String bookCategory;
     private String isbn;
     private String authorName;
     private String publisher;
     private Date publishedDate;
     private String fileSize;
     private String bookUrl;
     private String bookImage;
     private String readBy;
     private Integer totalPage;
     private String description;
     private Integer copy;
     private Set bookissues = new HashSet(0);

    public Book() {
    }

    public Book(String bookTitle, String bookCategory, String isbn, String authorName, String publisher, Date publishedDate, String fileSize, String bookUrl, String bookImage, String readBy, Integer totalPage, String description, Integer copy, Set bookissues) {
       this.bookTitle = bookTitle;
       this.bookCategory = bookCategory;
       this.isbn = isbn;
       this.authorName = authorName;
       this.publisher = publisher;
       this.publishedDate = publishedDate;
       this.fileSize = fileSize;
       this.bookUrl = bookUrl;
       this.bookImage = bookImage;
       this.readBy = readBy;
       this.totalPage = totalPage;
       this.description = description;
       this.copy = copy;
       this.bookissues = bookissues;
    }
   
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
    public String getBookTitle() {
        return this.bookTitle;
    }
    
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }
    public String getBookCategory() {
        return this.bookCategory;
    }
    
    public void setBookCategory(String bookCategory) {
        this.bookCategory = bookCategory;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public Date getPublishedDate() {
        return this.publishedDate;
    }
    
    public void setPublishedDate(Date publishedDate) {
        this.publishedDate = publishedDate;
    }
    public String getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }
    public String getBookUrl() {
        return this.bookUrl;
    }
    
    public void setBookUrl(String bookUrl) {
        this.bookUrl = bookUrl;
    }
    public String getBookImage() {
        return this.bookImage;
    }
    
    public void setBookImage(String bookImage) {
        this.bookImage = bookImage;
    }
    public String getReadBy() {
        return this.readBy;
    }
    
    public void setReadBy(String readBy) {
        this.readBy = readBy;
    }
    public Integer getTotalPage() {
        return this.totalPage;
    }
    
    public void setTotalPage(Integer totalPage) {
        this.totalPage = totalPage;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getCopy() {
        return this.copy;
    }
    
    public void setCopy(Integer copy) {
        this.copy = copy;
    }
    public Set getBookissues() {
        return this.bookissues;
    }
    
    public void setBookissues(Set bookissues) {
        this.bookissues = bookissues;
    }

       public List<Book> booksQuery(){
            Session session=hibernateUtil.HibernateUtil.openSession();
            Transaction transaction=null;
            session.beginTransaction();        
            Query query=session.createQuery("from Book");
            List<Book> bookList=(List<Book>)query.list();
            session.getTransaction().commit();
            session.close();               
            return bookList;
        }
         
    public Book getById(int id){
        Session session=hibernateUtil.HibernateUtil.openSession();
        Transaction transaction=null;
        session.beginTransaction();       
        Book b  =(Book) session.get(Book.class, id);                              
        return b;
    }
 
    public boolean reducBookCopy(int id){
            Session session=hibernateUtil.HibernateUtil.openSession();
            Transaction transaction=session.beginTransaction();        
             Book book=(Book)session.get(Book.class, id);                               
             book.setCopy(book.getCopy()-1);
             session.update(book);
             transaction.commit();
          return true;
     }


        public boolean deleteBook( int id){
           boolean result=false;
            Session session=hibernateUtil.HibernateUtil.openSession();
            Transaction transaction=session.beginTransaction();        
             Book book=(Book)session.get(Book.class, id);     
             if(book !=null){
                 result=true;
                  session.delete(book);
                  transaction.commit();
             }
             return result;
        }
     public Book updateBook(int bookId, String bookTitle,String isbn,String authorName,String publisher, int totalPage){
        Session session=hibernateUtil.HibernateUtil.openSession();
        Transaction transaction=session.beginTransaction();
        Book b=(Book)session.get(Book.class, bookId);
 
        b.setBookTitle(bookTitle);
        b.setIsbn(isbn);
        b.setAuthorName(authorName);
        b.setPublisher(publisher);
        b.setTotalPage(totalPage);

        
        session.update(b);
        transaction.commit();
        
        if(b!=null){
            return b;
        }
        return null;
     }


}


