package models;
// Generated Jun 23, 2015 12:50:21 AM by Hibernate Tools 3.6.0


import hibernateUtil.HibernateUtil;
import java.util.Date;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String email;
     private String userPassword;
     private Date birthDate;
     private String gender;
     private String mobile;
     private String location;
     private Date registrationDate;
     private String verified;

    public Member() {
    }

    public Member(String firstName, String lastName, String email, String userPassword, Date birthDate, String gender, String mobile, String location, Date registrationDate, String verified) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.userPassword = userPassword;
       this.birthDate = birthDate;
       this.gender = gender;
       this.mobile = mobile;
       this.location = location;
       this.registrationDate = registrationDate;
       this.verified = verified;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
    public String getVerified() {
        return this.verified;
    }
    
    public void setVerified(String verified) {
        this.verified = verified;
    }

public boolean register(models.Member reg){
        
        if(isExitsUser(reg)!=null ) return false;
            // 3. Get Session object
            Session session = hibernateUtil.HibernateUtil.openSession();
 
            // 4. Starting Transaction
            Transaction transaction = session.beginTransaction();
            session.save(reg);
            transaction.commit();
            session.close();
            return true;
    }
    public Member isExitsUser(Member reg){
            boolean result=false;
            Session session = hibernateUtil.HibernateUtil.openSession();
            // 4. Starting Transaction                  
            Transaction transaction = session.beginTransaction();
            Query q=session.createQuery("from Member where Email='"+reg.getEmail()+"'");
            Member regis=(Member)q.uniqueResult();
            if(regis !=null){
                return regis;
            }
            return null;
    }
        public Member getUserByUserId(String userId) {
        Session session = HibernateUtil.openSession();
        Transaction tx = null;
        Member user = null;
        try {
            tx = session.getTransaction();
            tx.begin();
            Query query = session.createQuery("from Member where Email='"+userId+"'");
            user = (Member)query.uniqueResult();
            tx.commit();
        } catch (Exception e) {
            if (tx != null) {
                tx.rollback();
            }
            e.printStackTrace();
        } finally {
            session.close();
        }
        return user;
    }
        
     public List<Member> getMembers(){
            Session session=hibernateUtil.HibernateUtil.openSession();
            Transaction transaction= session.beginTransaction();                   
            Query memberQuery=session.createQuery("from Member");
            List<Member> all=(List<Member>)memberQuery.list();
            transaction.commit();
            session.close();               
            return all;
    }   
     
     public Member updateProfile(int id, String firstName, String lastName, String email, String mobile, String password){
        Session session=hibernateUtil.HibernateUtil.openSession();
        Transaction transaction=session.beginTransaction();
        Member registration=(Member)session.get(Member.class, id);

        registration.setFirstName(firstName);
        registration.setLastName(lastName);
        registration.setEmail(email);
        registration.setMobile(mobile);
        registration.setUserPassword(password);
        session.update(registration);
        transaction.commit();
        
        return registration;
     }
     


}


